services:
  cryptofail-app:
    build: .
    container_name: safevault-cryptofail-container
    ports:
      - "8003:80"
    environment:
      DB_HOST: labsec-db
      DB_NAME: safevault_crypto
      DB_USER: root
      DB_PASS: labsec_root_2026
    networks:
      - labsec-network
    restart: unless-stopped

networks:
  labsec-network:
    external: true
