services:
  authfail-app:
    build: .
    container_name: securelogin-authfail-container
    ports:
      - "8006:80"
    environment:
      DB_HOST: labsec-db
      DB_NAME: securelogin_auth
      DB_USER: root
      DB_PASS: labsec_root_2026
    networks:
      - labsec-network
    restart: unless-stopped

networks:
  labsec-network:
    external: true
